name: Deploy ringamajig

on:
    push:
        branches:
            - master # or your deployment branch

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to server via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      set -ex
                      cd /srv/ringamajig
                      git pull origin master
                      npm install
                      npm run build
                      sudo systemctl restart ringamajig.service
